export const BASE_URL = "https://www.mobylmenu.com/api/";
export const STRIPE_SECRET_KEY = 'sk_test_51NLQ8IDwopSMzlySR8gzTmwgbmz8rifAKDPHUYStjNu7iY0aHOsMAzYjstf52HvZYkkEPXDjjfZvRLftY9mca7d300c16HZJ8L'
export const STRIPE_PUBLISHABLE_KEY = 'pk_test_51NLQ8IDwopSMzlySNuPSfsCgT2LWhmcfy1QYcIYKANJHAgCOd7EBFAsOSyLZRYh3ZIlWgUTYec1LAA7WAJXkAJVX00YRE9fffm'